apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-credentials
    namespace: cloudflared
type: Opaque
data:
    credentials.json: ENC[AES256_GCM,data:KHae+zcCmVdiZaXS0uGuVdbnwTVW+WlEKS5pmpEY1Q4rzZY7sSHwvLMbhgHIlG/5LMjTyH5N8+Znj9uq3I5PA9mpsxHR1Ju++AOEfOz4Hqcrtr1uaY5GiVH4NRuwdtSrHdDqEpBfmExUbVIyfJWwHaS5OLQUsy3f+GNfyyZBhQoWGCYd0KSLVLCYYkPIhql6ydeQnNclv++K/59IeP8Na7bdcHj1rFVT8XtAwNRxoEL2zOcaTVBaVHvhNJNNehlHsmY1ewIPAk7tTe7YVgVu2SwMn8DKMDd0pP3UBMEn0x1LvkICk4f5RU+m/2I=,iv:J9PsSbGx1cKUOZSyK5idWEfloARt02K+v+FPCAA2fSg=,tag:izmU/44Rs1QtyF15dociUA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLWFlZRkNibGUzdjhTaG5H
            R0NEMDI2bWdhZGpUUjRqS2NpMDlyU3hrc2hNCiswd29rZ0Y3YU9oVXMxWDljVGZn
            aCtWWTZpTm12dCtWNlFwRzlKaWJLaWsKLS0tIDRoY3hhK0o5cGFwTHFkUUptRUlP
            ejZOTi8wUzlTNmZCZWQ5NVlJeHFZNFkKURejYXpBuiwRXCWpzdh9d+Ip6ZwJxsYD
            ac3/GQtP1BiG+CIelpguDOBJU4wlx4zfof+bTogZtpvo1KIr4OtnTg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qv2n8jc4zrln84g2k34rum07u0z3crem2p652g4ghlxzhz3jxgqqdkxp4v
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-01T04:33:22Z"
    mac: ENC[AES256_GCM,data:UaMUd9EJcpjrj1Alwm03eEdQBKQslV5ARd+cju/my+pGcndQlEPWlQA1SriflrySWnQkAOAgLewfV7DGJP0F+RqIZ6zwZHtAmHW7UtVTyvmHQAIe0ppyT0C5F5ZqxPs2g5idBAJz1wZ6VrxxEfwh0yLY5fTmHKzm2lCiSi+H+AY=,iv:uob1fXgWKp78qQVJ9k/5aXSSNAnuZePem2SNJAIY5Fw=,tag:dA25T+Tp+2gu9rJU+1cf8g==,type:str]
    version: 3.13.3
