apiVersion: v1
kind: Secret
metadata:
    name: immich-db-backup-s3
    namespace: immich
type: Opaque
data:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:yL51DPyaRu39sTKwpBjGxbZQYGQRJlnToI4FCQ==,iv:sXD/FnPMgJOrzIHK3BXVXLe1u2oZNcjZW65TSjRXop8=,tag:2a7BQLkyxCog3/s9TK2wEg==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:SuKC+CZdI24Pj1Mg9x+G2fQSNScjOBkDTwuMRkiRvA5TMer2bcSaamLupTM0hd31LVLpgcdtjvI=,iv:lmGBvorDVRolZa9bAM5WcTuzCWBbxUBIninUbJWbsGM=,tag:5PHtoehecYhgQ0eqQaVwRA==,type:str]
    REGION: ENC[AES256_GCM,data:Loz2oe7/WbmOe2BLGUEcAw==,iv:vs+hjgx+FozrTEzgSM62imF8LQjEpJP5K4QaAifmqQ8=,tag:kWjT7wmDkP0X6rPKBkG5mQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWk4vbUl2QlBQQjFqZVd5
            MUN2RTkxVTZvNzUyNklMa1JLcUZpRjVYZ2k4ClRkQjE5MmxRNlQ1SmRJQ1RlTXVK
            SHVrb08rT0pCMGdSM0c4RDBYSSt6ZU0KLS0tIGM0S2R5dWtlNjJ0cTBPRHRCYWNX
            S285Y1JsTHJ5a2VRdHVpNTNUOUROME0KCEnCxwdyRcUhW6cNsfgk3bff5IwiQZyJ
            urqahG7Tm+wNTO5jybn6ILrJGbly+/x5+TggbNTgfP9TRcKxEDcsmQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qv2n8jc4zrln84g2k34rum07u0z3crem2p652g4ghlxzhz3jxgqqdkxp4v
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-01T04:33:22Z"
    mac: ENC[AES256_GCM,data:Vl6HmVadWBfmouu+EbnC3QbOx3wAZbcx8g47s/w/SQ5T+tIkvKjlj/DJZ2ZN2RZZLXetIgh7Nu/yT3b6DBUxrm8Barbf934vZEy9rdxoZwZBtbACLoKCH798E9b2CHTJ7QKJfcPN/grjednZIg5vbIxpYwj98Q/dIR2s6h8Ckd8=,iv:JpDESX1Bz4bQEyFnDhs00xvVwWBVN91G1vkM7B3KP4Y=,tag:L2cWBKQ3D5jUUA94jGkXHg==,type:str]
    version: 3.13.3
