apiVersion: v1
kind: Secret
metadata:
    name: immich-library-backup
    namespace: immich
type: Opaque
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:VWyMHbEBlIFEiIXSImRLD/p7V8ugqEuMZKZUEDT5ML/KBA1o,iv:3MfnJN3BuTj+w/S2eYa5qFIFooXsr6Ja7gdBDq4fsAY=,tag:fdiTm4zaABIqR8M6/pck/g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:6F7klhKDlPcQfS4vGzdNVLDO0BM7jTUpZRD+uofM8phcjWVjD3GULJkmmpA=,iv:p8iHIeVV/JBRDR/42Xjbp05C9PYvKGw8GYfan3+OnN0=,tag:mW37he5RvsQGJobXmjpeFA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:DR0d6RykrO6+KC41PKl9IvwUWwgtHIW4rpXmMt51a3DWn9Um5caZtDiN5q0cx5ZjbcM+tWBmleo7SY5f98BKOg==,iv:Ie5FloN5TEKycwmlA+6uSEPElMGkKoWZi39ECJP3+XA=,tag:necQ2QS/dh9x1StD4NR5sg==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:1noWZrPBESEr5NtJHxw35GEamKjRxF/pdqmlOf/yW7OoXHWq6eV7/OgdmzWWecZmo5GYp1CDEczr1y4mosIBbny+GkVmXUoWVCz/sNuYcXtHh6OtJrVottTuuIj5xreV,iv:0VfjEhXMyEY7vDJ01JxTA0AmK9B91kCJjmZUgSCftjw=,tag:NQ1HsP+hM5WX5SMG1ymnLg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpNXpuanE2R0xabHlYeFdN
            YzR2RzZBV1VSa3lqbVcycStiemhVeVNjcmswCnRCb2tmU1dLdXNJVE03TDNZT1Zw
            Tzh5ZGd2cDB2My92ZkZLbkxUTVBrUjAKLS0tIFZ2aWN2RUxkcGk1TDRZSDRCNFpZ
            RS9NTmNWcW1rZkdUMkNzQlhFNnNLZXcKqRKNjthwUE92k8ByxKh8A4BZmf9/4s/e
            KnCK4+wpBZXU4EexqdShz7pYD9EzVSWVV7oLZ57+gNuaZ0pMgj7DtA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qv2n8jc4zrln84g2k34rum07u0z3crem2p652g4ghlxzhz3jxgqqdkxp4v
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-01T04:33:22Z"
    mac: ENC[AES256_GCM,data:+ZaDU2aVV/hieGEa2PxIZJf+gXRsPfls3sWmtgt57d7IhiDrWsT+Np1iaVyBkhC3ZYJea9kSq6tswvIc6wMndOetLEJTUPTeByHU9gvbzKwJrEupxSt1WJu8CzhAfY4Ca7XXoCHmrHNamwgSkc4yUD5k1OPO2Mne10eLlsHGQPg=,iv:a2dlGhU2cWIoDL18Zv1C1lSNxzDMSHJFpWnK3yN6epM=,tag:KAemmgArVWw8j5y8uFUD5A==,type:str]
    version: 3.13.3
