apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:SH/ei39C+gX2X95lYlwBf/OG+lMrM47j74Xd6xVEykzBZQtC6p1AEX85c7Qyeu8BdUz1ZCKWqn5l5wosJk32sk9MPDN+1y+kJkbXRcw7ttsxYUW16lSMjPrA7OfcdRxuVJF37I81JvoF6PeSIw7CIdbKLJcNydE2BSuf/Jg5lIf4Rvhk1acM8lXlFyrt/TzMyLcPxgAQok//bOnlB6OUHle9yXwzlkE71tn7VLlRlzBz63CvugGvBvcIUKyZXBHkdpGKcCQmzRzOG3tH/jRMryiJGXJqOyLVyTCGf+N3n0iFyqF8sK1VidxQPvA=,iv:qBw+ZyOyKNR/ygmw8y3X4q0jC7jTQFWlCrueP/6+7XA=,tag:jZvRgwwPCh/mQtpbfM34BQ==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0YjJpNy9UZFo3UjNSTXZR
            akIrS1pNcEFGbjdQNmVCY0IrSGE0SWJWaGhFClp2YmgwbytaaVdjOWcvakJuWXdT
            enlwZVo2UGdEd0lSZTJ1R2Urd01hNnMKLS0tIFQ1WHRDK01tYXVoSFV5WmtVbCtu
            dVduM0FPQXYwYkJrbU5MS0dPTXZvT2MKlr/r7hEjTasU+PJZQYEbcLOXL19cLPWd
            ERQrE1DaHqyh3TtqUuImxkYlPAzxQbmsCFb+YwAcelAzwSUn9Lo0Iw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qv2n8jc4zrln84g2k34rum07u0z3crem2p652g4ghlxzhz3jxgqqdkxp4v
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T04:19:13Z"
    mac: ENC[AES256_GCM,data:RrX7mn99+TINnUa5uWtQHJbJNQgpaXdUKeLFDtZWClx5qv5W+kVdnnYxg343cv29ZobDN2GGMGYIJgF+bpXgLQqaBIcC+Ioka92kxqkcF18LFaU09yliaXJbYEoN+H2XSAwIds2IZDiTaNGkxOZQvZGZpgBo1pTD449hwBjGdgU=,iv:mKrXbGl/Gwa0rIGMrk5uZzNJDODWFdy/wI+EkKPNVGE=,tag:hDWYGpaJU4vzCDC8epz86w==,type:str]
    version: 3.13.3
