apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:ZukDC1sy9H0fYLouOcPI2PFiGXAwQe3CTjz/Bd7MMJ7VwHu8cCgATZU+fuWhD+VN3Qw/afaVxj98Kw8DoM/v0AwwQt7d6RXBC0W/FGQIrDPxfFn2yW/5aAUM/CP46oiLCJSWDQT/bNxjqjx6btueWUmIc+eoDGKg20T+NpAZts/zGUlpqym54cQPMKmtVnW/wAjmAYmz6TEeSMJscH7f1dVJveQ58IVHh/cmYDel8VfDTHjVAlq4jrgtQzhb0PoagIzVYUWpJ+1La0cjpIPbtJwcGJod70csoY4h+8E6yXBrEgmzj7HThxphF4g=,iv:8iuKzSbJPnWso4oGpjzdEoLOrPXRYAJdkKh4W/p0fO4=,tag:xbYHbZNM52hGSuQUMmv+cw==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxb3VTN1VrR28wQUNiakF0
            QXRseHl3MkFNOUdjQSsrNTZZQmo3VGNKZGxJCmZYOUU2bjBmOFowRFNHVzlkdzB3
            Uklib3p1eDY0Zmc3TFZhdklRMTV4SlkKLS0tIG9nSkVMaC8vUTBGb213OEZTRnQw
            ZDJtTFBXTnl1dmJYZ1BCNzA2MXp1aE0KpWsQLZfna2UIzO7xV1V+wWPHHPNC4NWs
            jaNsc/DPY2M6Q67zhoXISTfWDctupprx2PnNeDPpkIhFs27fhogc0Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qv2n8jc4zrln84g2k34rum07u0z3crem2p652g4ghlxzhz3jxgqqdkxp4v
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-13T15:12:21Z"
    mac: ENC[AES256_GCM,data:k+vec9zeKPO46j6SNZjircS6DV0eYvd7F6z0TnGasehPxZSPtwnBmkildsLO3RFZrnG6mr3cMNsCOcI8Hs+8p9UMUkohTHdDCwtOKpxyJ7DveU+u35hIgSWzSBdEQnIuv1/RO81COWGeoH3b1lj3I1u0c5+zZPmbWvCqAgyOSfE=,iv:raK6xkdkWg9mbz3KzQhYEfGvEQIetz0cDAWuYNj+WTs=,tag:SYZWfKPzcH8WjMzzpen0JA==,type:str]
    version: 3.13.2
