apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: immich
  namespace: immich
spec:
  interval: 12h
  url: oci://ghcr.io/immich-app/immich-charts/immich
  ref:
    tag: 0.13.2
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: ^https://token\.actions\.githubusercontent\.com$
        subject: ^https://github\.com/immich-app/immich-charts/\.github/workflows/release\.yaml@refs/tags/immich-
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 30m
  releaseName: immich
  chartRef:
    kind: OCIRepository
    name: immich
  values:
    controllers:
      main:
        containers:
          main:
            image:
              tag: v3.2.4
            env:
              DB_HOSTNAME:
                valueFrom:
                  secretKeyRef: {name: immich-database-app, key: host}
              DB_USERNAME:
                valueFrom:
                  secretKeyRef: {name: immich-database-app, key: user}
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef: {name: immich-database-app, key: password}
              DB_DATABASE_NAME:
                valueFrom:
                  secretKeyRef: {name: immich-database-app, key: dbname}

    valkey:
      enabled: true

    immich:
      persistence:
        library:
          existingClaim: immich-library-pvc

    server:
      service:
        main:
          type: LoadBalancer
      ingress:
        main:
          enabled: true
          className: traefik
          annotations: {}
          hosts:
            - host: immich.blayney.org
              paths:
                - path: "/"
                  service:
                    identifier: main
          tls: []
